### ISSUE TITLE
Remove `nk_` portion from the identifers

### ISSUE THREAD

**Issue by define-private-public** [zacharycarter/nuklear-nim#2]
It's safe to assume that whatever is found in `nuklear.nim` is well, part of Nuklear.  For what is exposed to Nim, I think it would be better to remove that `nk_` portion from the identifiers, ans then suggest that Nuklear be imported like so: `import nuklear as nk`.

For example, `nk.rgb()` looks much cleaner than `nk_rgb()`.

The only issue I can see if someone does `import nuklear` without the `as` portion and may have something conflict with a separate import.

**Comment by zacharycarter** [comment]
@define-private-public I've created a new branch for these changes : https://github.com/zacharycarter/nuklear-nim/tree/RemoveNKPrefixes

I'm also starting to create more Nimian bindings. See https://github.com/zacharycarter/nuklear-nim/blob/RemoveNKPrefixes/nuklear.nim#L1026

The prefix removal is done. The abstraction layer is going to take some time. If there is urgency to get the prefix removal in master, I can do so, just let me know.

**Comment by zacharycarter** [comment]
Closed with 1e97f1404e28abc9e1f06ff8bccadeb57163181a
