### ISSUE TITLE
Can you give me an example for Android?

### ISSUE THREAD

**Issue by kingofoz** [zacharycarter/nuklear-nim#4]
Hi @zacharycarter 
Can you please give us a demo for Android?

Thanks,
Yingjun

**Comment by zacharycarter** [comment]
Hi @kingofoz 

If I have time, possibly. I'm currently working on / maintaining several projects so the likelihood of this happening any time soon is rather slim.

Essentially what you'd need to do is write an OpenGL ES backend and then compile your application using the NDK toolchain.

Even if I were to provide an OpenGL ES backend, you'd still have to know how to do the latter to make it useful.

Have you ever built an android application with Nim? If not I'd start there. If so, then all you really need to do is take the existing backend I wrote and replace the GL calls with GLES calls.

If more folks are after something like this I'll consider putting some time into it, but for now I suggest trying to get an android app going if you haven't already, and if you have try to convert the existing backend to OpenGL ES. If you hit any blockers let me know and I can help.

**Comment by kingofoz** [comment]
Hi @zacharycarter 
Thanks for the quick response! Well, I haven't built an android app with Nim. Currently I am pretty new to Nim and OpenGL. I am afraid it is too difficult for me to write such a backend...
Do you use Nim heavily?

**Comment by zacharycarter** [comment]
@kingofoz I do - http://fragworks.io | http://github.com/fragworks/frag are my main projects using Nim atm.

Sorry for not replying sooner, been a busy weekend!

If you have any specific questions about developing android apps using Nim etc, please let me know and I can try to point you to some resources / offer some help. I'm also in #Nim irc and my name is also zacharycarter in there.

Thanks and have a good one!

**Comment by kingofoz** [comment]
@zacharycarter 
Thanks for the kind help. I will ask you if I have concrete questions about android dev. And, I have a glance at Frag, Lumix Engine and Urho3D(and Urhonimo). Do you have comments on them? Can you give me a feature list of Frag?

**Comment by kingofoz** [comment]
And, does Frag support Vulkan?

**Comment by zacharycarter** [comment]
@kingofoz sure -

At this point frag is pretty immature and I wouldn't recommend using it in any capacity besides playing around with it. I'm still building the first few games with it - so far I've cloned space invaders and now I'm working on an original title.

Out of the three engines you listed, I'd say Urho3D is the furthest along and most mature. Unfortunately the Urho3d bindings (Urhonimo) created by Araq - Nim's creator -  have fallen out of date, and no one has picked up the project to update them, as I imagine it's quite a bit of work.

Frag will support Vulkan as soon as BGFX properly supports it. FRAG like Lumix engine are both using bgfx for rendering. The main difference between the two is frag aims to be more similar to libgdx / lwjgl while lumix engine aims for a more unity-esque approach with nodes / components and a 3d scene graph.

Right now frag has no scene graph (although someone is working on one for it) and has no 3d support.

If you're interested in using frag I can provide direction but please note it will be hairy / and things may break without notice. It'd still be a great learning experience if your goal is to get into Nim / game programming / android programming with Nim. I'm also always looking for contributors for frag if you're interested in finding a project to work on.

I saw you poking around in #Nim the other night - I'd suggest hanging out there if Nim is of interest to you, and you can also (if you'd like) find a gitter dedicated to frag at https://gitter.im/fragworks/frag

**Comment by kingofoz** [comment]
@zacharycarter Thanks for the answer, very informative. I am always searching web to find a good game engine and a good GUI package. :-) Sometimes I don't know what kind of engine is suitable for me. Currently I am pretty new to Nim. I am not sure if I can do something for frag. Let's keep contact. I am sure I would keep an eye on Frag. :-)

**Comment by LotfiAghel** [comment]
hello
i'm game developer and for many years I need some language such as NIM,  with c++ performance and meta Programing (AST Macro) powers such as lisp. NIM is very good choice (seems better than rust).
i can help on OPENGL ES port i have plan for transpile or integrate COCOS2DX to nim .
but at first OPENGL ES dos not matter for beginner only sample for hello word for android is enough
