### ISSUE TITLE
Example Flickers and has a random line going throught the Title Bar

### ISSUE THREAD

**Issue by callowaysutton** [zacharycarter/nuklear-nim#8]
Running 64 Bit Zorin OS (Ubuntu 16.04) and whenever I compile the example and run it I am met with the example window that flickers and doesn't respond to any mouse clicks
Any ways I could fix this?

**Comment by zacharycarter** [comment]
I'm not surprised the example doesn't respond to mouse clicks - I don't think I put any input related code into the example. The example was more just to show how to write a backend for Nuklear with existing nim libraries, like the GLFW bindings.

I'm not sure about the flickering - I'll have to try to reproduce.

You could add the mouse input functionality yourself, or if i get time I will enhance the examples to include more of the example functionality from the official examples.

**Comment by CaptainKraft** [comment]
Is this resolved? I don't have this problem when I run the example.
